trigger:
  branches:
    include:
      - main
      - develop
      - release/*
      - hotfix/*
      - feature/*

pr:
  branches:
    include:
      - main
      - develop
      - release/*
      - hotfix/*
      - feature/*

stages:
- stage: Build
  jobs:
    - job: Build
      steps:
        - script: echo "Build step"

- stage: DeployToProduction
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
    - deployment: DeployProd
      environment: 'Production'
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo "Deploying to Production"
